title: William Everett
description: Finance | Analytics | CS @ Gtown
site_title: '@wae10 - William Everett'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wae10
# blog_url: 
email: wae10@georgetown.edu
linkedin: https://www.linkedin.com/in/william-e-bbb94013b
insta_username: everettwill
# reddit_username: 

# absolute or relative
profile_picture: 

# Google Analytics ID
google_analytics: 