title: William Everett
description: Finance & CS/Analytics @ Georgetown University
site_title: '@wae10 - William Everett'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wae10
# blog_url: 
email: wae10@georgetown.edu
# keybase_username: 
# twitter_username: 
# reddit_username: 

# absolute or relative
profile_picture: 

# Google Analytics ID
google_analytics: 