title: William Everett
description: Finance | Computer Science
site_title: 'William Everett'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: wae10
# blog_url: 
email: willeverett13@gmail.com
linkedin: https://www.linkedin.com/in/weverett
insta_username: everettwill
# reddit_username: 

# absolute or relative
profile_picture: 

# Google Analytics ID
google_analytics: G-2NCNHQ77FE
link: https://www.googletagmanager.com/gtag/js?id=G-2NCNHQ77FE
